version: '3.1'
services:
  app:
    container_name: app
    image: 'lottery-system:latest'
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql

  dbpostgresql:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lottery
